name: CI Pipeline

on:
  push:
    branches:
      - samuelbuitrago
  pull_request:
    branches:
      - samuelbuitrago

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies
      run: mvn install

    - name: Run tests
      run: mvn test
      continue-on-error: true  # Este paso no fallará el workflow si las pruebas fallan.

    - name: Build project
      run: mvn package
